### PR TITLE
Move --repository-config to all commands acting on Git repositories

### PR DESCRIPTION
**Pull request by sbesson**
This change allows to use command like `update-submodules` with a YML configuration file. The use case is a job to update https://github.com/ome/bio-formats-build submodules since `bioformats` is on a different tracking branch.

Proposed tag: `0.11.0`

### CODE REVIEW

**Comment by sbesson** [comment]
See https://github.com/ome/bio-formats-build/pull/26 for an example of automated PR opened consuming this change using https://github.com/ome/bio-formats-build/blob/master/scripts/repositories.yml 

Also included 5593286 which is a breaking formatting change for the commit message (`#` are now rendered as `-` see PR above). When it comes to creating PRs using a single commit message, it prevents `#` being rendered as Markdown heading. If acceptable, I would propose to call this `0.11.0`. Otherwise it should be possible to make the  `PullRequest` string representation configurable.

**Comment by joshmoore** [comment]
:+1: the formatting of the opened PR. My only potential concern here would be that some of the other commands which have now inherited `--repository-config` won't be able to handle it. From my POV, that's something we can piece apart down the road. Cheers.

**Comment by joshmoore** [comment]
No objection to the version number. Leaving you to merge/tag/release.

**Comment by sbesson** [comment]
Cheers. Will tag and release (also including the Travis based PyPI deployment).

**Pull request merged**
