### PR TITLE
Quick fix for missing field

### PR DESCRIPTION
**Pull request by joshmoore**
A newly forked repository by @olatarkowska
led to the following error:

```
  File ".../site-packages/scc/git.py", line 1935, in get_merge_remotes
    if repo.private:
AttributeError: 'NoneType' object has no attribute 'private'
```

### CODE REVIEW

**Comment by manics** [comment]
> `AttributeError: 'NoneType' object has no attribute 'private'`

Doesn't that mean `repo` was `None`?

**Comment by sbesson** [comment]
In this specific case, it looks like the GitHub PullRequest API returns `null` for the head repo of: see https://api.github.com/repos/openmicroscopy/openmicroscopy/pulls/5936. The expectation is that `head.repo` will return the head repo e.g. see https://api.github.com/repos/openmicroscopy/openmicroscopy/pulls/5900. This might have been caused by a deletion/reforking of the upstream repository.

My concern with this situation is that we might propagate the `AttributeError` since the library does not know which remote should be fetched and merged.

**Comment by joshmoore** [comment]
> Doesn't that mean repo was None?

You're right, but `hasattr` is None safe.

> My concern with this situation is that we might propagate the AttributeError since the library will not know which remote should be fetched and merged.

My hope was mostly to get a (green?) branch that I could point jenkins for testing but have been sidelined today.

**Comment by joshmoore** [comment]
Build is green. Merging and pushing out a 0.10.2 to see if I can get jenkins green. If we need to do a 0.10.3 later today, we can.

**Pull request merged**
