### PR TITLE
report conflicting PRs in visually separate block from merges

### PR DESCRIPTION
**Pull request by mtbc**
I keep missing conflicts because they are within a visually distinct block starting "Merged PRs:" even though they are not merged.

### CODE REVIEW

**Comment by mtbc** [comment]
I have no idea what the Travis failure means.

**Comment by manics** [comment]
Might be a travis bug? I'm seeing failures on other repos e.g. https://travis-ci.org/IDR/deployment/builds/255797765:
```
The command "cd ansible; molecule test" exited with 0.

Done. Your build exited with 1.
```

**Comment by joshmoore** [comment]
Pushed a commit. Let's see if that let's travis pass.

**Comment by mtbc** [comment]
It does, thank you!

**Comment by joshmoore** [comment]
You're welcome. Leaving you to drive this further.

**Comment by sbesson** [comment]
Tested using today's openmicroscopy:

```
    merge develop -Dorg -Snone
    
    Repository: openmicroscopy/openmicroscopy
    Excluded PRs:
      # PR 5407 jburel 'table new api' (exclude comment)
      # PR 5405 manics 'Cleanup locks if plpgsql ome_nextval fails (experimental)' (exclude comment)
    Already up-to-date.
    
    Merged PRs:
      # PR 4619 joshmoore 'Load all `omero/plugins` subdirs on the PYTHONPATH'
      # PR 4974 jburel 'make movie'
      # PR 4983 sbesson 'Clean up unnecessary bio-formats dependency'
      # PR 5297 emilroz 'OMERO.tables Image and Well metadata support'
      # PR 5315 will-moore 'Api experimenters groups'
      # PR 5352 will-moore 'privileges canChgrp'
      # PR 5377 dominikl 'Fixed some light admin issues'
      # PR 5398 mtbc 'increase timeout for integration test cleanup in teardown'
      # PR 5400 will-moore 'Fix training print encode error'
      # PR 5406 rgozim 'public_get_only'
      # PR 5425 dominikl 'Adminfacility privileges'
      # PR 5427 sbesson 'Allow the local Maven repository to be overriden '
      # PR 5432 rgozim 'Fix empty project filter'
      # PR 5434 dominikl 'Reverse intensity rename Insight/Web'
      # PR 5435 dominikl 'Deprecate ReverseIntensityMap/Context'
      # PR 5440 jburel 'helper method change'
    
    Conflicting PRs (not included):
      # PR 5428 rgozim 'Fix left panel'
    
    Repository: ome/scripts
    Already up-to-date.
```

Additionally , all [tests are passing](https://ci.openmicroscopy.org/job/SCC-merge/915/) with this included. All good. Are you looking for an immediate release as `0.7.1` @mtbc ?

**Comment by mtbc** [comment]
If it wouldn't be much trouble then it would be lovely if our CI merge job console logs could indeed start reflecting this.

**Pull request merged**
