### PR TITLE
Add --repository-config option to set base branch for submodules

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Testing:

- clone `https://github.com/ome/bio-formats-build.git`
- build and install scc
- run `scc merge --repository-config=repos.yml master --no-ask --reset --update-gitmodules -D none -I user:rleigh-codelibre -v` for example
- the configuration can be used recursively if submodules contain submodules (add a `submodules` section alongside `base-branch` in the submodule definition).  The dict for the submodule will be passed to submodule `GitRepository` initialisation.

`repos.yml` example:

```
base-branch: master

submodules:
  ome-common-java:
    base-branch: master

  bioformats:
    base-branch: develop
    
  bio-formats-autogen:
    base-branch: master
    
  bio-formats-bundles:
    base-branch: master
    
  bio-formats-documentation:
    base-branch: master
    
  bio-formats-imagej:
    base-branch: master
    
  bio-formats-matlab:
    base-branch: master
    
  bio-formats-test:
    base-branch: master
    
  ome-codecs:
    base-branch: master
    
  ome-common-java:
    base-branch: master
    
  ome-jai:
    base-branch: master
    
  ome-mdbtools:
    base-branch: master
    
  ome-metakit:
    base-branch: master
    
  ome-model:
    base-branch: master
    
  ome-poi:
    base-branch: master
    
  ome-stubs:
    base-branch: master
```

### CODE REVIEW

**Comment by manics** [comment]
FYI there are some long-standing requests for scc and omego to support a config file to save having to define common args on the command line, e.g.
- https://github.com/ome/omego/pull/76
- https://github.com/ome/omego/issues/39
- https://github.com/openmicroscopy/yaclifw/pull/7

**Comment by manics** [comment]
I only mentioned it because of the naming of the new parameter `--config` which sounds quite generic.

**Comment by rleigh-codelibre** [comment]
Yes, it could be renamed to something more specific.  Or, we could allow more than branch configuration in the future.  For example, it could be extended to support per-repository filtering options etc.

**Comment by rleigh-codelibre** [comment]
Renamed `--config` to `--repository-config`.  I used "repository" rather than "branch" because it's more related to repositories regarding submodules and base branches.

**Comment by sbesson** [comment]
The changes proposed here make sense, are overall backwards-compatible while allowing more granularity on the control of some of the filter options via a YML configuration file. The support for file-based flexible configuration is something that has been discussed as a more generic feature (see https://github.com/openmicroscopy/yaclifw/pull/7) and having such a concrete driver is a good first step.

Assuming the unit and integration tests pass, happy for this to be released as 0.9.0.

NB: as an extra feature, should I open a PR to port to `scc` the project-wide `VERSION` strategy implemented in `omego` in https://github.com/ome/omego/pull/114. Depending on the timeline, this should be completely safe to be pushed to a follow-up patch release.

**Pull request merged**
