### PR TITLE
Better has_local_changes implementation

### PR DESCRIPTION
**Pull request by joshmoore**
Propose release as v0.9.4

### CODE REVIEW

**Comment by sbesson** [comment]
Successfully tested via https://web-proxy.openmicroscopy.org/east-ci/job/SCC-merge/PYTHON=python,label=testintegration/9/console. Merging for patch release

**Comment by sbesson** [comment]
As https://github.com/openmicroscopy/snoopycrimecop/pull/232 was merged but not released, I'll release as `0.10.0` if that's okay with you.

**Comment by sbesson** [comment]
Released as https://pypi.org/project/scc/0.10.0/

**Comment by joshmoore** [comment]
> if that's okay with you.

:+1:

**Pull request merged**
