### PR TITLE
scc: Modernise to run with python 2 or 3

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Requires further integration testing.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [SCC-merge#967](https://ci.openmicroscopy.org/job/SCC-merge/967/). See the [console output](https://ci.openmicroscopy.org/job/SCC-merge/967/consoleText) for more details.
Possible conflicts:
  - PR #232 joshmoore 'external-issues: new command for listing non-team issues'
    - scc/main.py

--conflicts

**Comment by rleigh-codelibre** [comment]
Close temporarily for testing new job.

**Comment by rleigh-codelibre** [comment]
Reopen with pytest version fix.

**Comment by rleigh-codelibre** [comment]
Closing temporarily while I work on some corrections.

**Pull request closed without merging**
