### PR TITLE
Pass no_wait=True since communicate() will handle the wait

### LINKED ISSUE #197: Conflict resolution can hang on large diffs
See https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-docs/615/console

For very large diffs (like the copyright PR modifying all files in the repository), the `git diff` operation seems to hang.

/cc @manics

### PR DESCRIPTION
**Pull request by manics**
Without this the process will hang since the stdout buffer will be filled.
Closes #197

### CODE REVIEW

**Comment by manics** [comment]
```
bioformats$ scc merge -D all develop

2015-01-09 17:47:13,144 [   scc.merge] INFO  Merging Pull Request(s) based on develop
2015-01-09 17:47:13,145 [   scc.merge] INFO  Including Pull Request(s) opened by any user
2015-01-09 17:47:37,099 [     scc.git] INFO    # PR 857 melissalinkert 'Initial support for Zeiss .lms files'
Conflicting PR.
Possible conflicts:
  - Upstream changes
    - components/formats-api/src/loci/formats/readers.txt
2015-01-09 17:47:37,734 [     scc.git] INFO    # PR 1015 qidane 'Messy binary'
Conflicting PR.
Possible conflicts:
  - Upstream changes
    - components/formats-bsd/src/loci/formats/out/OMETiffWriter.java
2015-01-09 17:47:38,059 [     scc.git] INFO    # PR 1161 sommerc 'Initial CellH5 Reader class'
Conflicting PR.
Possible conflicts:
  - Upstream changes
    - components/bio-formats-plugins/src/loci/plugins/util/ROIHandler.java
2015-01-09 17:47:39,206 [     scc.git] INFO    # PR 1443 joshmoore 'Genshi ZIP'
Conflicting PR.
Possible conflicts:
  - PR #1177 rleigh-dundee 'specification: Add metadata for HDF5 embedding'
    - ant/xsd-fu.xml
  - PR #1426 qidane 'Initial Rendering Definitions schema'
    - ant/xsd-fu.xml
2015-01-09 17:47:41,204 [     scc.git] INFO    # PR 1510 snoopycrimecop 'Update copyright headers'
Conflicting PR.
Possible conflicts:
  - PR #1500 bjoernthiel 'take new dimensions into account'
    - components/formats-bsd/src/loci/formats/in/OBFReader.java
2015-01-09 17:47:42,566 [   scc.merge] INFO  Repository: openmicroscopy/bioformats
2015-01-09 17:47:42,566 [   scc.merge] INFO  Already up-to-date.
2015-01-09 17:47:42,566 [   scc.merge] INFO  
2015-01-09 17:47:42,566 [   scc.merge] INFO  Merged PRs:
2015-01-09 17:47:42,566 [   scc.merge] INFO    # PR 858 melissalinkert 'Initial support for Veeco AFM data'
2015-01-09 17:47:42,566 [   scc.merge] INFO    # PR 1177 rleigh-dundee 'specification: Add metadata for HDF5 embedding'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1309 melissalinkert 'Allow tile-based access of large JPEG-2000 images'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1381 melissalinkert 'Parse physical pixel sizes from CellSens .vsi datasets'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1407 melissalinkert 'TIFF: fix plane count calculation for pyramids with multiple planes'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1426 qidane 'Initial Rendering Definitions schema'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1479 qidane 'Updated XSLT for units conversion'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1500 bjoernthiel 'take new dimensions into account'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1501 rleigh-dundee 'FormatReader/FormatTools Modulo improvements'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1502 melissalinkert 'Inveon: fix offsets for files larger than 2GB'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1507 melissalinkert 'Add note about running data tests on Windows'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1508 melissalinkert 'Revert to using java.text.SimpleDateFormat for retrieving timestamps'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1512 rleigh-dundee 'C++: Generalise tile buffer/cache/coverage support'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1513 hflynn 'Re-arranging troubleshooting info'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1514 melissalinkert 'Parse SignificantBits from OME-XML/OME-TIFF files'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1518 sbesson 'Fix link to Leica LAS AF Lite software'
2015-01-09 17:47:42,567 [   scc.merge] INFO  Conflicting PRs (not included):
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 857 melissalinkert 'Initial support for Zeiss .lms files'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1015 qidane 'Messy binary'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1161 sommerc 'Initial CellH5 Reader class'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1443 joshmoore 'Genshi ZIP'
2015-01-09 17:47:42,567 [   scc.merge] INFO    # PR 1510 snoopycrimecop 'Update copyright headers'
2015-01-09 17:47:42,567 [   scc.merge] INFO  
```

**Comment by manics** [comment]
Longer term... maybe it's time for some refactoring:
- rewrite `GitRepository.communicate` to use `no_wait`, and add options to only capture `stdout` instead of `stdout` and `stderr`
- replace all `p=GitRepository.call() ... p.communicate()` calls with `GitRepository.communicate`

**Comment by sbesson** [comment]
The refactoring proposal in https://github.com/openmicroscopy/snoopycrimecop/pull/201#issuecomment-69473995 sounds sensible to me. Should we to use this PR as the placeholder? Or should we merge this and carry out the refactoring somewhere else?

**Comment by manics** [comment]
Might as well do it here, if it turns out to be more difficult than expected I can always revert.

**Comment by sbesson** [comment]
Looks good to me. Using `GitRepository.communicate()` across the board may also fix transient `rc=128` errors like in https://ci.openmicroscopy.org/job/SCC-merge/530/. Thoughts about leaving this PR open for an additional week and check for the test output? Or are you waiting for this to go in to work on other changes?

**Comment by manics** [comment]
It can stay open for testing.

**Pull request merged**
